### ISSUE TITLE
Real-time problem

### ISSUE THREAD

**Issue by ImYannChan** [AlbusPeter/MeshFlow_Video_Denoising#2]
Would you like to ask, can the method in this paper realize real-time processing of video streams? Or what frame rate can be achieved?

**Comment by AlbusPeter** [comment]
Unoptimized and unparalleled code can achieve around 4 fps at 1920 × 1080. More details are in the [paper](https://albuspeter.github.io/projects/Meshflow-video-denoising/Meshflow-video-denoising.pdf).
