### ISSUE TITLE
video image stabilization

### ISSUE THREAD

**Issue by fkjkey** [AlbusPeter/MeshFlow_Video_Denoising#3]
meshflow started out as a video stabilization project. Can we denoise and stabilize images at the same time

**Comment by fkjkey** [comment]
@AlbusPeter Excuse me, do you do video stabilization

**Comment by AlbusPeter** [comment]
> meshflow started out as a video stabilization project. Can we denoise and stabilize images at the same time

Yes. You can utilize video stabilization as the matching method. Then, you can achieve both tasks at the same time.
